# Generated by Django 5.1.4 on 2024-12-28 12:37

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number1', models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('phone_number2', models.CharField(blank=True, default='', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('email', models.EmailField(default='employee@example.com', max_length=254, unique=True)),
                ('address', models.TextField(default='Address not provided')),
                ('aadhar', models.CharField(blank=True, default='', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{12}$')])),
                ('bank_account_number', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator('^\\d{9,18}$')])),
                ('upi_id', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('department', models.CharField(default='HR', max_length=100)),
                ('hire_date', models.DateField(default=django.utils.timezone.localdate)),
                ('photo', models.ImageField(default='default_employee_photo.jpg', upload_to='employees/')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('phone_number_1', models.CharField(default='', max_length=10)),
                ('phone_number_2', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
                ('service_type', models.CharField(max_length=50)),
                ('installation_address', models.TextField(default='')),
                ('solar_details', models.TextField(blank=True, default='')),
                ('panel_type', models.CharField(blank=True, default='not_decided', max_length=50)),
                ('roof_type', models.CharField(blank=True, default='not_decided', max_length=50)),
                ('system_size', models.FloatField(default=0.0)),
                ('energy_consumption', models.FloatField(default=0.0)),
                ('solar_budget', models.FloatField(default=0.0)),
                ('site_assessment', models.BooleanField(default=False)),
                ('financing_options', models.BooleanField(default=False)),
                ('installation_preference', models.CharField(blank=True, default='not_decided', max_length=50)),
                ('solar_comments', models.TextField(blank=True, default='')),
                ('cctv_details', models.TextField(blank=True, default='')),
                ('premises_type', models.CharField(blank=True, default='home', max_length=50)),
                ('num_cameras', models.TextField(default=0)),
                ('camera_type', models.CharField(blank=True, default='ip', max_length=50)),
                ('recording_storage', models.CharField(blank=True, default='7_days', max_length=50)),
                ('mobile_monitoring', models.BooleanField(default=False)),
                ('on_site_monitoring', models.BooleanField(default=False)),
                ('remote_access', models.BooleanField(default=False)),
                ('power_source', models.CharField(blank=True, default='ac_power', max_length=50)),
                ('existing_network', models.BooleanField(default=False)),
                ('budget_range', models.CharField(blank=True, default='0', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SolarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppenquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
