# Generated by Django 5.1.4 on 2025-01-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_project_category_alter_project_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='camera_type',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='cctv_details',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='energy_consumption',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='existing_network',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='financing_options',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='installation_preference',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='mobile_monitoring',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='on_site_monitoring',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='panel_type',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='power_source',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='recording_storage',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='remote_access',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='roof_type',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='site_assessment',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='solar_details',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='system_size',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='budget_range',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='installation_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='num_cameras',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number_1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='premises_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='service_type',
            field=models.CharField(choices=[('solar', 'Solar'), ('cctv', 'CCTV')], max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='solar_budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='solar_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
