# Generated by Django 5.1.4 on 2025-01-02 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_enquiry_options_remove_enquiry_camera_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={},
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='installation_address',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='referral_code',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='installation_address_cctv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='installation_address_solar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='budget_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='premises_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Office', 'Office'), ('Retail Store', 'Retail Store'), ('Warehouse', 'Warehouse'), ('Factory', 'Factory')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='service_type',
            field=models.CharField(choices=[('select_service', 'Select Service'), ('solar', 'Solar'), ('cctv', 'CCTV'), ('Network System and Networking', 'Network System and Networking')], max_length=50),
        ),
    ]
