# Generated by Django 5.1.4 on 2025-01-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_enquiry_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
