# Generated by Django 5.1.4 on 2025-01-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cctv', 'CCTV'), ('solar', 'Solar'), ('whatsapp', 'WhatsApp')], max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
