# Generated by Django 5.1.4 on 2025-01-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('CCTV', 'CCTV'), ('Solar', 'Solar'), ('WhatsApp', 'WhatsApp')], max_length=20),
        ),
    ]
