# Generated by Django 5.1.4 on 2025-01-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_request_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='installation_address_cctv',
            new_name='installation_address',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='installation_address_solar',
        ),
    ]
