# Generated by Django 5.1.4 on 2025-01-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contact_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_enquiry',
            name='additional_comments',
            field=models.TextField(blank=True, default='', verbose_name='Additional Comments'),
        ),
        migrations.AlterField(
            model_name='contact_enquiry',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='contact_enquiry',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='contact_enquiry',
            name='phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Phone Number'),
        ),
    ]
